### ISSUE TITLE
About completion of this project

### ISSUE THREAD

**Issue by Iipython** [quocdat32461997/Mask_RCNN#3]
I'am very excited when I find this project because the code style is concise and logical. I am a beginner of both tensorflow2 and mask-rcnn,and I want to know whether this is a finished mask-rcnn(minimal implementation is ok) or not now?

**Comment by quocdat32461997** [comment]
> I'am very excited when I find this project because the code style is concise and logical. I am a beginner of both tensorflow2 and mask-rcnn,and I want to know whether this is a finished mask-rcnn(minimal implementation is ok) or not now?

hi @Iipython, thanks for your words.

Yes, the project is not finished yet. I started 3 months ago, and I had been busy with internship. I have just finish the internship; that means I may finish this project by mid Nov.
